CustomerBillDetails/Models/Item.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerBillDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemRate { get; set; }
    }
}

CustomerBillDetails/Controllers/BillController.cs
using CustomerBillDetails.Models;
using CustomerBillDetails.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerBillDetails.Controllers
{
    public class BillController : Controller
    {
        // GET: Bill
        public ActionResult Index()
        {
            BillRepository billRepository = new BillRepository();
            ModelState.Clear();
            return View(billRepository.GetBill());
        
        }

        public ActionResult Dropdown()
        {
            customer_detailsEntities2 myentity = new customer_detailsEntities2();
            var getItemList = myentity.Items.ToList();
            SelectList list = new SelectList(getItemList, "ItemId", "ItemName");
            ViewBag.ItemNameList = list;
            return View();
        }

        // GET: Bill/Details/5
        public ActionResult Details(int id)
        {
            BillRepository billRepository = new BillRepository();
            return View(billRepository.GetBill().Find(bill => bill.BillId == id));
        }

        // GET: Bill/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bill/Create
        [HttpPost]
        public ActionResult Create(BillModel objBillModel,List<DetailModel> objDetailModelList)
        {
            //, DetailModel objDetailModel
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    //BillRepository billRepository = new BillRepository();

                    //if (billRepository.AddBill(objBillModel))
                    //{
                    //    ViewBag.Message = "Bill details added successfully";
                    //}
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Edit/5
        public ActionResult Edit(int id)
        {
            BillRepository billRepository = new BillRepository();
            return View(billRepository.GetBill().Find(bill => bill.BillId == id));
        }

        // POST: Bill/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, BillModel obj)
        {
            try
            {
                // TODO: Add update logic here
                BillRepository billRepository = new BillRepository();

                billRepository.UpdateBill(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bill/Delete/5
        [HttpPost]
        public ActionResult Delete(int Id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                BillRepository billRepository = new BillRepository();
                if (billRepository.DeleteBill(Id))
                {
                    ViewBag.AlertMsg = "Bill details deleted successfully";

                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public JsonResult AddItemDetails(List<BillModel> persons)
        {
            //to do something
            string data = "";
            foreach (BillModel person in persons)
            {
                data += person.objDetailModel.ItemName; 
            }
            return Json(data);
        }

    }
}

CustomerBillDetails/Controllers/ItemController.cs
using CustomerBillDetails.Models;
using CustomerBillDetails.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerBillDetails.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult Index()
        {
            ItemRepository itemRepository = new ItemRepository();
            ModelState.Clear();
            return View(itemRepository.GetItem());
        }

        // GET: Item/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Item/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Item/Create
        [HttpPost]
        public ActionResult Create(ItemModel obj,FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    ItemRepository itemRepository = new ItemRepository();

                    if (itemRepository.AddItem(obj))
                    {
                        ViewBag.Message = "Item added successfully";
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Edit/5
        public ActionResult Edit(int id)
        {
            ItemRepository itemRepository = new ItemRepository();



            return View(itemRepository.GetItem().Find(obj => obj.ItemId == id));
        }

        // POST: Item/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ItemModel obj, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                ItemRepository itemRepository = new ItemRepository();

                itemRepository.UpdateItem(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Item/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                ItemRepository itemRepository = new ItemRepository();
                if (itemRepository.DeleteItem(id))
                {
                    ViewBag.AlertMsg = "Item deleted successfully";

                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

CustomerBillDetails/Views/Item/Create.cshtml
@model CustomerBillDetails.Models.ItemModel


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h1>Add Item</h1>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
            </div>
        </div>
            -->

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Create", "Bill")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CustomerBillDetails/Views/Item/Delete.cshtml
@model CustomerBillDetails.Models.ItemModel
<h1>Delete Item</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemRate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomerBillDetails/Views/Item/Edit.cshtml
@model CustomerBillDetails.Models.ItemModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h1>Edit Item</h1>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CustomerBillDetails/Views/Item/Index.cshtml
@model IEnumerable<CustomerBillDetails.Models.ItemModel>

<h1>Item List</h1>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemRate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemRate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
            <!--@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) | -->
            @Html.ActionLink("Delete", "Delete", new { id=item.ItemId})
        </td>
    </tr>
}

</table>