CustomerBillDetails/Controllers/DetailController.cs
using CustomerBillDetails.Models;
using CustomerBillDetails.Repository;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerBillDetails.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        public ActionResult Index()
        {
            DetailRepository detailRepository = new DetailRepository();
            ModelState.Clear();
            return View(detailRepository.GetAll());
        }

        // GET: Detail/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Detail/Create
        public ActionResult Create()
        {
            DetailRepository detailRepository = new DetailRepository();
            dynamic mymodel = new ExpandoObject();

            return View();
        }

        // POST: Detail/Create
        [HttpPost]
        public ActionResult Create(DetailModel obj)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    DetailRepository detailRepository = new DetailRepository();

                    if (detailRepository.AddDetail(obj))
                    {
                        ViewBag.Message = "Bill details added successfully";
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Detail/Edit/5
        public ActionResult Edit(int id)
        {
            DetailRepository detailRepository = new DetailRepository();
            return View(detailRepository.GetAll().Find(obj => obj.BillDetailsId == id));
        }

        // POST: Detail/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DetailModel obj, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                DetailRepository detailRepository = new DetailRepository();

                detailRepository.Update(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Detail/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Detail/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                DetailRepository detailRepository = new DetailRepository();
                if (detailRepository.Delete(id))
                {
                    ViewBag.AlertMsg = "Details deleted successfully";

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public JsonResult AddItemDetails(List<DetailModel> persons)
        {
            //to do something
            string data = "";
            foreach (DetailModel person in persons)
            {
                data += person.ItemName;
            }
            return Json(data);
        }

    }
}

CustomerBillDetails/Views/Detail/Create.cshtml
@model CustomerBillDetails.Models.DetailModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add Details</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BillDetailsId, new { htmlAttributes = new { @class = "form-control" } })

        <div class="col-md-2">
            <div class="form-group">

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ItemName, null, "id_itemname", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ItemName, "Select Item Name", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, null, "id_quantity", new { htmlAttributes = new { onchange = "getTotal()", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "Quantity", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ItemRate, null, "id_rate", new { htmlAttributes = new { onchange = "getTotal()", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ItemRate, "Item Rate", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Total, null, "id_total", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Total, "Total", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(model => model.BillId, new { htmlAttributes = new { @class = "form-control" } })
        <div>
            <div class="form-group">
                <div class="col-md-offset-2">
                    <input type="button" value="ADD" class="btn btn-default" id="btnAddRow" />
                    <input type="submit" value="Save" class="btn btn-default" id="btnSave"/>
                </div>
            </div>
        </div>

        <table id="detailTable" border="1" width="80%">
            <thead>
                <tr style="font-weight:bold;">
                    <th>Item Name</th>
                    <th>Item Quantity</th>
                    <th>Item Rate</th>
                    <th>Item Total</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>


}

<!--
    <div>
    @Html.ActionLink("Back to List", "Index", "Detail")
    </div>
-->
@section scripts
{
    <script>
        function getTotal() {
            value1 = parseInt(document.getElementById("id_quantity").value);
            value2 = parseInt(document.getElementById("id_rate").value);
            if (!value1 == "" && !value2 == "") {
                sum = value1 * value2;
                document.getElementById("id_total").value = sum;
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $("#btnAddRow").click(function () {
                debugger;
                //Getting value from to populate
                var name = $("#id_itemname").val();
                var quantity = $("#id_quantity").val();
                var rate = $("#id_rate").val();
                var total = $("#id_total").val();

                //Prepare TR to add in Table
                var tr;
                tr = $('<tr/>');
                tr.append("<td>" + name + "</td>");
                tr.append("<td>" + quantity + "</td>");
                tr.append("<td>" + rate + "</td>");
                tr.append("<td>" + total + "</td>");
                $('#detailTable').append(tr);
                document.getElementById("id_itemname").value = '';
                document.getElementById("id_quantity").value = '';
                document.getElementById("id_rate").value = '';
                document.getElementById("id_total").value = '';

            });
        });
    </script>
    <script type="text/javascript">
        $("#btnSave").click(function() {
            console.log("btnSave Triggered!");

            var persons = new Array();
            $("#detailTable tbody tr").each(function () {
                var row = $(this);
                var person = {};
                person.ItemName = row.find("td").eq(0).html();
                person.Quantity = row.find("td").eq(1).html();
                person.ItemRate = row.find("td").eq(2).html();
                person.Total = row.find("td").eq(3).html();
                persons.push(person);
            });

            $.ajax({
                type: "POST",
                url: "/Detail/AddItemDetails",
                data: JSON.stringify(persons),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    alert(data);
                }
            });

        });
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

CustomerBillDetails/Views/Detail/Delete.cshtml
@model CustomerBillDetails.Models.DetailModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetailModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillDetailsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillDetailsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomerBillDetails/Views/Detail/Edit.cshtml
@model CustomerBillDetails.Models.DetailModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DetailModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BillDetailsId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillDetailsId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillDetailsId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CustomerBillDetails/Views/Detail/Index.cshtml
@model IEnumerable<CustomerBillDetails.Models.DetailModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BillDetailsId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BillId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BillDetailsId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BillId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>